name: 'backend-build-test'
on: # rebuild any PRs, manually triggered workflow runs and main branch changes
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    name: Run builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
        working-directory: ./backend
      - run: |
          npm run build
        working-directory: ./backend
  test: # make sure the action works on a clean machine without building
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm test
        working-directory: ./backend